services:
  bolide_backend:
    build: backend
    restart: always
    networks:
      - bolide_network

  bolide_frontend:
    build: bolide_front
    restart: always
    networks:
      - bolide_network
  bolide_tunnel:
    image: cloudflare/cloudflared
    restart: always
    command: tunnel run
    networks:
      - bolide_network
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
networks:
  bolide_network:
    driver: bridge
